import { defineConfig } from "eslint/config";
import configs from "eslint-config-webpack/configs.js";

export default defineConfig([
  {
    extends: [configs["recommended-dirty"]],
  },
]);
// This file is auto-generated by `@webpack-contrib/eslint-config-webpack`.